version: ' 27.1.1'

services:
  db:
    container_name: 'ichiisoft-local-wordpress-db'
    image: 'mysql:5.7'
    volumes:
      - './data/mysql:/var/lib/mysql'
    ports:
      - '18766:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'somewordpress'
      MYSQL_DATABASE: 'ichiisoft_wordpress_db'
      MYSQL_USER: 'ichiisoft_wordpress_user'
      MYSQL_PASSWORD: 'ichiisoft_wordpress_password'

  wordpress:
    container_name: 'ichiisoft-local-wordpress'
    depends_on:
      - db
    image: 'wordpress:latest'
    ports:
      - '8080:80'
    environment:
      WORDPRESS_DB_HOST: 'db:3306'
      WORDPRESS_DB_USER: 'ichiisoft_wordpress_user'
      WORDPRESS_DB_PASSWORD: 'ichiisoft_wordpress_password'
      WORDPRESS_DB_NAME: 'ichiisoft_wordpress_db'
    volumes:
      - './ichiisoft:/var/www/html'
      - './plugins:/var/www/html/wp-content/plugins'

  phpmyadmin:
    image: 'phpmyadmin/phpmyadmin'
    container_name: 'ichiisoft-local-phpmyadmin'
    ports:
      - '8081:80'
    environment:
      PMA_HOST: 'db'
      PMA_PORT: '3306'
      PMA_USER: 'ichiisoft_wordpress_user'
      PMA_PASSWORD: 'ichiisoft_wordpress_password'
    depends_on:
      - db
